name: Petclinic CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Build application using Maven
      - name: Maven Build
        run: |
          mvn clean package -DskipTests

      # 4. Run tests
      - name: Maven Test
        run: |
          mvn test

      # 5. SonarQube Analysis
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar \
            -Dsonar.projectKey=petclinic-cicd \
            -Dsonar.projectName=petclinic-cicd \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      # 6. Upload WAR to Nexus
      - name: Upload WAR to Nexus
        run: |
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
          --upload-file target/*.war \
          "${{ secrets.NEXUS_REPO_URL }}/repository/petclinic-cicd/petclinic-cicd.war"

      # 7. Download WAR from Nexus
      - name: Download WAR from Nexus
        run: |
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
          -o petclinic-cicd.war \
          "${{ secrets.NEXUS_REPO_URL }}/repository/petclinic-cicd/petclinic-cicd.war"

      # 8. Copy WAR to Tomcat server
      - name: Deploy WAR to Tomcat
        run: |
          curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
          -T petclinic-cicd.war \
          "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/Petclinic-cicd&update=true"
          "${{ secrets.TOMCAT_URL }}/manager/text/deploy?path=/petclinic-cicd&update=true"
